# Generated by Django 4.2.16 on 2024-11-13 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dz3', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='answers_like',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='questions_like',
        ),
        migrations.AddField(
            model_name='answerlike',
            name='profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dz3.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='answer_likes',
            field=models.ManyToManyField(blank=True, default=0, related_name='answer_likes', to='dz3.answerlike'),
        ),
        migrations.AddField(
            model_name='profile',
            name='question_likes',
            field=models.ManyToManyField(blank=True, default=0, related_name='question_likes', to='dz3.questionlike'),
        ),
        migrations.AddField(
            model_name='questionlike',
            name='profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dz3.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='answerlike',
            unique_together={('mark', 'profile')},
        ),
        migrations.AlterUniqueTogether(
            name='questionlike',
            unique_together={('mark', 'profile')},
        ),
    ]
